{{ if .Values.enableDeployment }}
  {{  $httpPort := .Values.HTTPPorts }}
  {{  $httpsPort := .Values.HTTPSPorts }}
  {{ if .Values.HTTPTargetPorts }} {{ $httpPort = .Values.HTTPTargetPorts }} {{ end }}
  {{ if .Values.HTTPSTargetPorts }} {{ $httpsPort = .Values.HTTPSTargetPorts }} {{ end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d{{ .Values.version }}{{- if .Values.subset }}{{- print "-" .Values.subset }}{{- end }}
  labels:
    app: d{{.Values.version}}
spec:
  selector:
    matchLabels:
      app: p{{.Values.version}}
  template:
    metadata:
      labels:
        app: p{{.Values.version}}
        version: {{ default "default" .Values.subset  }}
      annotations:
        app: p{{.Values.version}}
        {{- range $index,$node := (lookup "v1" "Node" "" "").items }}
        node{{ add $index 1}}: {{ $node.metadata.name }}
    {{- end }}
    spec:
      containers:
        - name: exp
          image: "watergist/k8s-exps:base-http"
          ports:
            {{- if $httpPort }}
            {{- range $index,$value := regexSplit "~+" ($httpPort | toString) -1 }}
            - containerPort: {{ $value | int }}
              name: http-{{ $value}}
            {{- end }}
            {{- end }}
            {{- if $httpsPort }}
            {{- range $index,$value := regexSplit "~+" ($httpsPort | toString) -1 }}
            - containerPort: {{ $value | int }}
              name: https-{{ $value }}
          {{- end }}
          {{- end }}
          imagePullPolicy: Always
          env:
            - name: HTTP_PORTS
              value: {{ $httpPort | quote }}
            - name: HTTPS_PORTS
              value: {{ $httpsPort | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_PROPERTIES_PATH
              value: &propertiesPath /wd/config/pod-info
            - name: TLS_KEYPAIR_PATH
              value: &keyPairPath {{ if .Values.tlsSecret }} /wd/config/tls {{ end }}
            {{- if .Values.env }}
            {{- range $index,$value := regexSplit "~+" (.Values.env | toString | nospace) -1 }}
            {{- $kv := regexSplit "=+" $value -1 }}
            - name: {{ index $kv 0 }}
              value: {{ index $kv 1 | quote}}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: pod-info
              mountPath: *propertiesPath
            {{- if .Values.tlsSecret }}
            - name: tls-secrets
              mountPath: *keyPairPath
      {{- end }}
      volumes:
        {{- if .Values.tlsSecret }}
        - name: tls-secrets
          secret:
            secretName: {{ .Values.tlsSecret }}
        {{- end }}
        - name: pod-info
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
  {{end}}