apiVersion: apps/v1
kind: Deployment
metadata:
  name: d{{ .Values.version }}{{ (include "getSubset" .) }}
  labels:
    app: d{{.Values.version}}
spec:
  selector:
    matchLabels:
      app: p{{.Values.version}}
  template:
    metadata:
      labels:
        app: p{{.Values.version}}
        version: {{ default "default" .Values.subset  }}
      annotations:
        app: p{{.Values.version}}
        {{- range $index,$node := (lookup "v1" "Node" "" "").items }}
        node{{ add $index 1}}: {{ $node.metadata.name }}
    {{- end }}
    spec:
      containers:
        - name: exp
          image: "watergist/k8s-exps:base-http"
          ports:
            {{- if .Values.HTTPTargetPorts }}
            {{- range $index,$value := regexSplit "~+" (.Values.HTTPTargetPorts | toString) -1 }}
            - containerPort: {{ $value | int }}
              name: http-{{ $value}}
            {{- end }}
            {{- end }}
            {{- if .Values.HTTPSTargetPorts }}
            {{- range $index,$value := regexSplit "~+" (.Values.HTTPSTargetPorts | toString) -1 }}
            - containerPort: {{ $value | int }}
              name: https-{{ $value }}
          {{- end }}
          {{- end }}
          imagePullPolicy: Always
          env:
            - name: HTTP_PORTS
              value: {{ .Values.HTTPTargetPorts | quote }}
            - name: HTTPS_PORTS
              value: {{ .Values.HTTPSTargetPorts | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_PROPERTIES_PATH
              value: &propertiesPath /wd/config/pod-info
            - name: TLS_KEYPAIR_PATH
              value: &keyPairPath /wd/config/tls
          volumeMounts:
            - name: pod-info
              mountPath: *propertiesPath
            {{- if .Values.tlsSecret }}
            - name: tls-secrets
              mountPath: *keyPairPath
            {{- end }}
      volumes:
        {{- if .Values.tlsSecret }}
        - name: tls-secrets
          secret:
            secretName: {{ .Values.tlsSecret }}
        {{- end }}
        - name: pod-info
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
