{{- $HTTPContainerPorts := regexSplit "~+" (.Values.HTTPTargetPorts | toString) -1 }}
{{- $HTTPSContainerPorts := regexSplit "~+" (.Values.HTTPSTargetPorts | toString) -1 }}
apiVersion: v1
kind: Service
metadata:
  name: s{{.Values.version}}
  labels:
    app: s{{.Values.version}}
spec:
  selector:
    app: p{{.Values.version}}
  ports:
    {{- if .Values.HTTPPorts }}
    {{- range $index,$value := regexSplit "~+" (.Values.HTTPPorts | toString) -1 }}
    - protocol: TCP
      port: {{ $value | int }}
      targetPort: {{ index $HTTPContainerPorts $index }}
      name: http-{{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.HTTPSPorts }}
    {{- range $index,$value := regexSplit "~+" (.Values.HTTPSPorts | toString) -1 }}
    - protocol: TCP
      port: {{ $value | int }}
      targetPort: {{ index $HTTPSContainerPorts $index }}
      name: https-{{ $value }}
    {{- end }}
  {{- end }}
  type: LoadBalancer
