{{ if .Values.enableService }}
  {{- $HTTPTargetPortsArray := regexSplit "~+" (.Values.HTTPTargetPorts | toString) -1 }}
  {{- $HTTPSTargetPortsArray := regexSplit "~+" (.Values.HTTPSTargetPorts | toString) -1 }}
apiVersion: v1
kind: Service
metadata:
  name: s{{.Values.version}}
  labels:
    app: s{{.Values.version}}
spec:
  selector:
    app: p{{.Values.version}}
  ports:
    {{- if .Values.HTTPPorts }}
    {{- range $index,$value := regexSplit "~+" (.Values.HTTPPorts | toString) -1 }}
    - protocol: TCP
      port: {{ $value | int }}
      targetPort: {{ if $.Values.HTTPTargetPorts }} {{ index $HTTPTargetPortsArray $index | int }} {{ else }} {{ $value | int }} {{ end }}
      name: http-{{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.HTTPSPorts }}
    {{- range $index,$value := regexSplit "~+" (.Values.HTTPSPorts | toString) -1 }}
    - protocol: TCP
      port: {{ $value | int }}
      targetPort: {{ if $.Values.HTTPSTargetPorts }} {{ index $HTTPSTargetPortsArray $index | int }} {{ else }} {{ $value | int }} {{ end }}
      name: https-{{ $value }}
  {{- end }}
  {{- end }}
  type: LoadBalancer

  {{end}}