apiVersion: apps/v1
kind: Deployment
metadata:
  name: d{{ .Values.version }}{{ (include "getSubset" .) }}
  labels:
    app: d{{.Values.version}}
spec:
  selector:
    matchLabels:
      app: p{{.Values.version}}
  template:
    metadata:
      labels:
        app: p{{.Values.version}}
        version: {{ default "default" .Values.subset  }}
      annotations:
        app: p{{.Values.version}}
        {{- range $index,$node := (lookup "v1" "Node" "" "").items }}
        node{{ add $index 1}}: {{ $node.metadata.name }}
        {{- end }}
    spec:
      containers:
        - name: exp
          image: "watergist/k8s-exps:base"
          ports:
            {{- if .Values.httpTargetPorts }}
            {{- range $index,$value := regexSplit "~+" .Values.httpTargetPorts -1 }}
            - containerPort: {{ $value | int }}
              name: http-{{ $value}}
            {{- end }}
            {{- end }}
            {{- if .Values.httpsTargetPorts }}
            {{- range $index,$value := regexSplit "~+" .Values.httpsTargetPorts -1 }}
            - containerPort: {{ $value | int }}
              name: https-{{ $value }}
            {{- end }}
            {{- end }}
          imagePullPolicy: Always
          env:
            - name: HTTP_PORTS
              value: {{ .Values.httpTargetPorts  }}
            - name: HTTPS_PORTS
              value: {{ .Values.httpsTargetPorts }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_PROPERTIES_PATH
              value: &propertiesPath /config/pod-info
          volumeMounts:
          - name: pod-info
            mountPath: *propertiesPath
          {{- if .Values.tlsSecret }}
          - name: tls-secrets
            mountPath: /config/tls
          {{- end }}
      volumes:
        {{- if .Values.tlsSecret }}
        - name: tls-secrets
          secret:
            secretName: {{ .Values.tlsSecret }}
        {{- end }}
        - name: pod-info
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
