{{ if .Values.enableDeployment }}
{{  $udpPort := .Values.UDPPort }}
  {{  $tcpPort := .Values.TCPPort }}
  {{ if .Values.UDPTargetPort }} {{ $udpPort = .Values.UDPTargetPort }} {{ end }}
  {{ if .Values.TCPTargetPort }} {{ $tcpPort = .Values.TCPTargetPort }} {{ end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d{{ .Values.version }}{{- if .Values.subset }}{{- print "-" .Values.subset }}{{- end }}
  labels:
    app: d{{.Values.version}}
spec:
  selector:
    matchLabels:
      app: p{{.Values.version}}
  template:
    metadata:
      labels:
        app: p{{.Values.version}}
        version: {{ default "default" .Values.subset  }}
      annotations:
        app: p{{.Values.version}}
        {{- range $index,$node := (lookup "v1" "Node" "" "").items }}
        node{{ add $index 1}}: {{ $node.metadata.name }}
    {{- end }}
    spec:
      containers:
        - name: exp
          image: "watergist/k8s-exps:base-l4"
          imagePullPolicy: Always
          ports:
            {{- if $tcpPort }}
            - containerPort: {{ $tcpPort }}
              protocol: TCP
              name: tcp-{{ $tcpPort }}
            {{- end }}
            {{- if $udpPort }}
            - containerPort: {{ $udpPort }}
              protocol: UDP
              name: udp-{{ $udpPort }}
          {{- end }}
          env:
            - name: UDP_PORT
              value: {{ $udpPort | quote }}
            - name: TCP_PORT
              value: {{ $tcpPort | quote}}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
  {{end}}