{{if .Values.enableService}}
apiVersion: v1
kind: Service
metadata:
  name: s{{.Values.version}}
  labels:
    app: s{{.Values.version}}
spec:
  selector:
    app: p{{.Values.version}}
  ports:
    {{- if .Values.TCPPort }}
    - protocol: TCP
      port: {{ .Values.TCPPort }}
      targetPort: {{ if .Values.TCPTargetPort }} {{ .Values.TCPTargetPort | int }} {{ else }} {{ .Values.TCPPort | int }} {{ end }}
      name: tcp-{{ .Values.TCPPort }}
    {{- end }}
    {{- if .Values.UDPPort }}
    - protocol: UDP
      port: {{ .Values.UDPPort }}
      targetPort: {{ if .Values.UDPTargetPort }} {{ .Values.UDPTargetPort | int }} {{ else }} {{ .Values.UDPPort | int }} {{ end }}
      name: udp-{{ .Values.UDPPort }}
    {{- end }}
  type: LoadBalancer
  {{end}}