apiVersion: v1
kind: Service
metadata:
  name: s{{.Values.version}}
  namespace: {{ .Values.expName }}
  labels:
    app: s{{.Values.version}}
spec:
  selector:
    app: p{{.Values.version}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      name: http-80
  type: LoadBalancer

